name: Build fip-player
run-name: Building fip-player
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install golang libmpv-dev
      - uses: actions/checkout@v3
      - run: go build .
      - run: git tag -f latest
      - uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Nightly build"
          files: fip-player
